[package]
name = "censorbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tbot = "0.6.6"
tokio = { version = "0.2", features = ["macros", "sync"] }
meval = "0.2"
tiny_id = "0.1.4"